# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Origin to Pointer
email: otp@stackd.com
description: > # this means to ignore newlines until "baseurl:"
  A behind the scenes look at the building of Stackd.com.
  Subscribe to our email list for infrequent updates.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://origintopointer.com" # the base hostname & protocol for your site
twitter_username: origintopointer

# Build settings
markdown: kramdown

permalink: /seasons/:title
